name: publish nuget packages

on:
  push:
    tags:
    - '*'
      
jobs:
    build:
    
        runs-on: windows-latest
        
        steps:
            - uses: actions/checkout@v1
            
            - name: Setup .NET Core
              uses: actions/setup-dotnet@v1
              with:
                dotnet-version: 5.0.100
                
            - name: Set env
              run: echo "DOTNET_CLI_TELEMETRY_OPTOUT=1" >> $GITHUB_ENV
              
            - name: Clean
              run: |
                dotnet clean ./src/Microservice.Library.sln --configuration Release
                dotnet nuget locals all --clear
              
            - uses: dotnet/nbgv@master
              id: nbgv
                
            - name: BuildWithPack
              run: |
                set version=${{ steps.nbgv.outputs.BuildingRef }}-alpha-g${{steps.nbgv.outputs.GitCommitIdShort}}
                set version=%version:~10%
                dotnet build ./src/NuGet/Library.All/Library.All.csproj -c Release -p:PackageVersion=${version}
              
            - name: Pack all-in-one-packages
              run:  |
                set version=${{ steps.nbgv.outputs.BuildingRef }}-alpha-g${{steps.nbgv.outputs.GitCommitIdShort}}
                set version=%version:~10%
                dotnet pack ./src/NuGet/Library.All/Library.All.csproj -c Release --no-build -p:PackageVersion=${version}
